<?php

namespace app\models;

use app\components\FormRendererDefinition;
use app\components\FormRendererTrait;
use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class PaymentForm extends Model implements FormRendererDefinition
{
    use FormRendererTrait;

    public $amount;
    public $payerName;
    public $payerMobile;
    public $description;
    public $verifyCode;
    public $filled = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
                [['amount', 'payerName', 'payerMobile'], 'required'],
                [['amount'], 'number', 'min' => 100],
                [['payerName', 'payerMobile', 'description'], 'string'],
                [['filled'], 'safe'],
            // verifyCode needs to be entered correctly
//            ['verifyCode', 'captcha', 'skipOnEmpty' => false, 'captchaAction' => '/payment/captcha'],
        ];
    }

    public function beforeValidate()
    {
        $this->amount = str_replace(',', '', $this->amount);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
                'payerName' => trans('words', 'Payer Name'),
                'payerMobile' => trans('words', 'Payer Mobile'),
                'amount' => trans('words', 'Amount'),
                'description' => trans('words', 'Description'),
        ];
    }

    public function formAttributes()
    {
        return [
                [
                        ['payerName', 'payerMobile'],
                        [
                                'type' => self::FORM_FIELD_TYPE_TEXT,
                                'template' => '{input}<span class="required">إلزامي *</span>',
                                'options' => ['class' => ' ']
                        ]
                ],
                'amount' => [
                        'type' => self::FORM_FIELD_TYPE_TEXT,
                        'template' => '{input}<span class="required">إلزامي *</span>',
                        'options' => ['class' => 'digitFormat'],
                        'hint' => trans('words', 'Rials')
                ]
        ];
    }
}