<?php

namespace app\models;

use app\components\MainController;
use app\controllers\PostController;
use app\controllers\ListController;
use Arcanedev\Arabic\DateTime;
use Yii;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * This is the model class for table "item".
 *
 * @property int $publish_date
 * @property int $summary
 */
class Post extends Item
{
    const TYPE_NEWS = 1;
    const TYPE_ARTICLE = 2;

    public static $modelName = 'post';

    public static $typeLabels = [
            self::TYPE_NEWS => 'news',
            self::TYPE_ARTICLE => 'article'
    ];

    public function getTypeLabel($type = false)
    {
        if (!$type) {
            $type = $this->type;
        }
        return trans('words', ucfirst(self::$typeLabels[$type]));
    }

    public static function getTypeLabels()
    {
        $lbs = [];
        foreach (self::$typeLabels as $key => $label) {
            $lbs[$key] = trans('words', ucfirst($label));
        }
        return $lbs;
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'item';
    }

    public function init()
    {
        parent::init();
        $this->dynaDefaults = array_merge($this->dynaDefaults, [
                'body' => ['CHAR', ''],
                'image' => ['CHAR', ''],
                'page_image' => ['CHAR', ''],
                'publish_date' => ['CHAR', ''],
                'summary' => ['CHAR', ''],
                'seen' => ['INTEGER', ''],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return array_merge(parent::rules(), [
                [['body', 'image', 'page_image', 'formCategories'], 'required'],
                [['summary'], 'string'],
                [['publish_date'], 'safe'],
                ['seen', 'default', 'value' => 0],
                ['publish_date', 'default', 'value' => time()],
                [
                        'modelID',
                        'default',
                        'value' => isset(Yii::$app->controller->models[self::$modelName]) ? Yii::$app->controller->models[self::$modelName] : null
                ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
                'body' => trans('words', 'Body'),
                'image' => trans('words', 'Image'),
                'page_image' => trans('words', 'Page Image'),
                'publish_date' => trans('words', 'Publish Date'),
                'summary' => trans('words', 'Summary'),
        ]);
    }

    /**
     * {@inheritdoc}
     * @return ItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ItemQuery(get_called_class());
    }

    public static function validQuery()
    {
        return self::find()->valid()->andWhere(['<=', self::columnGetString('publish_date'), time()]);
    }

    public function getComments_count()
    {
        return 0;
    }

    public function getUrl()
    {
        return Url::to(['/post/show', 'id' => $this->id, 'title' => encodeUrl($this->name)]);
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

    }

    public function formAttributes()
    {
        return array_merge(parent::formAttributes(), [
            'type' => [
                'type' => static::FORM_FIELD_TYPE_SELECT,
                'items' => \app\models\Post::getTypeLabels()
            ],
            'formCategories' => [
                'type' => static::FORM_FIELD_TYPE_SELECT,
                'items' => Category::getWithType(Category::CATEGORY_TYPE_NEWS),
                'options' => ['prompt' => trans('words', 'Select Category')]
            ],
            'publish_date' => [
                'type' => static::FORM_FIELD_TYPE_DATE,
                'options' => ['class' => 'form-control m-input m-input--solid', 'autocomplete' => 'off']
            ],
            'summary' => [
                'type' => static::FORM_FIELD_TYPE_TEXT_AREA,
                'containerCssClass' => 'col-sm-12',
            ],
            'body' => [
                'type' => static::FORM_FIELD_TYPE_TEXT_EDITOR,
                'containerCssClass' => 'col-sm-12',
                'options' => [
                    'options' => ['rows' => 30]
                ]
            ],
            'image' => [
                'type' => static::FORM_FIELD_TYPE_DROP_ZONE,
                'containerCssClass' => 'col-sm-6',
                'temp' => MainController::$tempDir,
                'path' => PostController::$imageDir,
                'filesOptions' => PostController::$imageOptions,
                'options' => [
                    'url' => Url::to(['upload-image']),
                    'removeUrl' => Url::to(['delete-image']),
                    'sortable' => false, // sortable flag
                    'sortableOptions' => [], // sortable options
                    'htmlOptions' => ['class' => 'single', 'id' => Html::getInputId(new self(), 'image')],
                    'options' => [
                        'createImageThumbnails' => true,
                        'addRemoveLinks' => true,
                        'dictRemoveFile' => 'حذف',
                        'addViewLinks' => true,
                        'dictViewFile' => '',
                        'dictDefaultMessage' => 'جهت آپلود تصویر کلیک کنید',
                        'acceptedFiles' => 'png, jpeg, jpg',
                        'maxFiles' => 1,
                        'maxFileSize' => 0.5,
                    ],
                ]
            ],
            'page_image' => [
                'type' => static::FORM_FIELD_TYPE_DROP_ZONE,
                'containerCssClass' => 'col-sm-6',
                'temp' => MainController::$tempDir,
                'path' => PostController::$imageDir,
                'filesOptions' => PostController::$imageOptions,
                'options' => [
                    'url' => Url::to(['upload-image']),
                    'removeUrl' => Url::to(['delete-image']),
                    'sortable' => false, // sortable flag
                    'sortableOptions' => [], // sortable options
                    'htmlOptions' => ['class' => 'single', 'id' => Html::getInputId(new self(), 'page_image')],
                    'options' => [
                        'createImageThumbnails' => true,
                        'addRemoveLinks' => true,
                        'dictRemoveFile' => 'حذف',
                        'addViewLinks' => true,
                        'dictViewFile' => '',
                        'dictDefaultMessage' => 'جهت آپلود تصویر کلیک کنید',
                        'acceptedFiles' => 'png, jpeg, jpg',
                        'maxFiles' => 1,
                        'maxFileSize' => 0.5,
                    ],
                ]
            ],
            'gallery' => [
                'type' => static::FORM_FIELD_TYPE_DROP_ZONE,
                'containerCssClass' => 'col-sm-12',
                'temp' => MainController::$tempDir,
                'path' => Attachment::getAttachmentPath(),
                'filesOptions' => PostController::$galleryOptions,
                'options' => [
                    'url' => Url::to(['upload-attachment']),
                    'removeUrl' => Url::to(['delete-attachment']),
                    'sortable' => false, // sortable flag
                    'sortableOptions' => [], // sortable options
                    'htmlOptions' => ['class' => '', 'id' => Html::getInputId(new self(), 'gallery')],
                    'options' => [
                        'createImageThumbnails' => true,
                        'addRemoveLinks' => true,
                        'dictRemoveFile' => 'حذف',
                        'addViewLinks' => true,
                        'dictViewFile' => '',
                        'dictDefaultMessage' => 'جهت آپلود تصاویر کلیک کنید',
                        'acceptedFiles' => 'png, jpeg, jpg',
                        'maxFiles' => 10,
                        'maxFileSize' => 0.5,
                    ],
                ]
            ],
        ]);
    }

    /**
     * @param bool $thumb
     * @return string
     */
    public function getImageSrc($thumb = false)
    {
        return Yii::$app->request->getBaseUrl() . '/' . PostController::$imageDir . '/' . ($thumb ? 'thumbs/100x100/' : '') . $this->image;
    }

    /**
     * @param bool $thumb
     * @return string
     */
    public function getPageImageSrc($thumb = false)
    {
        return $this->page_image ? Yii::$app->request->getBaseUrl() . '/' . PostController::$imageDir . '/' . ($thumb ? 'thumbs/100x100/' : '') . $this->page_image : null;
    }

    public function getDate($timestamp = false)
    {
        $timestamp = $timestamp ?: $this->publish_date;
        switch (app()->language) {
            case 'fa':
                return \jDateTime::date('Y/m/d', $timestamp);
            case 'en':
                return date('Y/m/d', $timestamp);
            case 'ar':
                $d = new DateTime();
                $d->setTimestamp($timestamp);
                return $d->hijriDate($timestamp, false, ':year/:month/:day');
        }
        return null;
    }

    public function beforeSave($insert)
    {
        if ($this->publish_date) {
            $this->publish_date = substr($this->publish_date, 0, 10);
        }

        return parent::beforeSave($insert);
    }

    public function getPublishDate()
    {
        if(app()->language == 'fa')
            return \jDateTime::date('Y/m/d', $this->publish_date);
        else
            return date('Y/m/d', $this->publish_date);
    }

    /**
     * @param integer $limit
     * @param integer|null $except
     * @return Post[]
    */
    public static function getLatestItems($limit = 10, $except = null)
    {
        $query = self::find()->limit($limit);

        if($except)
            $query->andWhere(['!=', 'id', $except]);

        return $query->valid()->all();
    }
}
